name: Build APK AMG Prototipe

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Buat Struktur Android & Update Kotlin
        run: |
          rm -rf android
          flutter create . --platforms=android --org=com.amg.prototipe --project-name=amg_prototipe
          
          # Menaikkan versi Kotlin ke 1.9.22 agar tidak bentrok
          find android -name "build.gradle*" -exec sed -i "s/ext.kotlin_version = .*/ext.kotlin_version = '1.9.22'/g" {} +
          find android -name "settings.gradle*" -exec sed -i 's/id "org.jetbrains.kotlin.android" version "[^"]*"/id "org.jetbrains.kotlin.android" version "1.9.22"/g' {} +

      - name: Ambil Dependensi
        run: flutter pub get

      - name: Kompilasi APK Android
        run: flutter build apk --debug

      - name: Upload File APK
        uses: actions/upload-artifact@v4
        with:
          name: amg-prototipe-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
