name: Build APK AMG Prototipe

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'

      - name: Lengkapi Berkas Sistem Android Otomatis
        run: |
          flutter create . --platforms=android --org=com.amg.prototipe

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: amg-prototipe-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
